"""edit migrations

Revision ID: e72db14970f2
Revises: 89884d2b0667
Create Date: 2023-09-03 18:26:48.514520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72db14970f2'
down_revision: Union[str, None] = '89884d2b0667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'rooms', 'hotels', ['hotel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    # ### end Alembic commands ###
